services:
  - type: web
    name: nfa-dfa-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: ALLOWED_ORIGINS
        value: "*"
    healthCheckPath: /

sites:
  - type: static
    name: nfa-dfa-frontend
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    publishDir: frontend/dist
